<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>sapphire</string>
    <key>scopeName</key>
    <string>source.spp</string>
    <key>fileTypes</key>
    <array>
      <string>spp</string>
    </array>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#comments</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#keywords</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#literals</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#operators</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#types</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#punctuation</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>keywords</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b((var)|(func)|(extern)|(ffi)|(operator)|(class))\b</string>
            <key>name</key>
            <string>storage.type.spp</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b((for)|(in)|(if)|(else)|(then)|(while)|(return)|(init)|(deinit))\b</string>
            <key>name</key>
            <string>keyword.control.spp</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(new)\b</string>
            <key>name</key>
            <string>keyword.operator.spp</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(this)\b</string>
            <key>name</key>
            <string>variable.language.this.spp</string>
          </dict>
        </array>
      </dict>
      <key>literals</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>string.quoted.double.spp</string>
            <key>begin</key>
            <string>"</string>
            <key>end</key>
            <string>"</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.begin.spp</string>
              </dict>
            </dict>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.end.spp</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>\\(\\|[nt"])</string>
                <key>name</key>
                <string>constant.character.escape.spp</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>match</key>
            <string>\b([0-9]+)\b</string>
            <key>name</key>
            <string>constant.numeric.spp</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(0x[0-9a-fA-F]+)\b</string>
            <key>name</key>
            <string>constant.numeric.spp</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(0b[0-1]+)\b</string>
            <key>name</key>
            <string>constant.numeric.spp</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b([0-9]*.[0-9]+)\b</string>
            <key>name</key>
            <string>constant.numeric.spp</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(nil)\b</string>
            <key>name</key>
            <string>constant.language.spp</string>
          </dict>
        </array>
      </dict>
      <key>operators</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>((\+)|(\-)|(\*)|(/)|(%)|(&lt;&lt;)|(&gt;&gt;)|(==)|(=)|(\!=)|(\!)|(&lt;)|(&lt;=)|(&gt;)|(&gt;=)|(\&amp;)|(\|)|(~)|(\&amp;\&amp;)|(\|\|)|(\?))</string>
            <key>name</key>
            <string>keyword.operator.spp</string>
          </dict>
        </array>
      </dict>
      <key>types</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b((int)|(string)|(uint)|(bool)|(byte)|(real))\b</string>
            <key>name</key>
            <string>entity.name.type.spp</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(ref)\b</string>
            <key>name</key>
            <string>storage.modifier.spp</string>
          </dict>
        </array>
      </dict>
      <key>punctuation</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>;</string>
            <key>name</key>
            <string>punctuation.terminator.spp</string>
          </dict>
          <dict>
            <key>match</key>
            <string>,</string>
            <key>name</key>
            <string>punctuation.separator.delimiter.comma.spp</string>
          </dict>
          <dict>
            <key>name</key>
            <string>punctuation.separator.dot-access.spp</string>
          </dict>
          <dict>
            <key>name</key>
            <string>punctuation.separator.dot-access.spp</string>
          </dict>
          <dict>
            <key>name</key>
            <string>punctuation.separator.colon.spp</string>
          </dict>
        </array>
      </dict>
      <key>comments</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>/\*</string>
            <key>captures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.spp</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\*/</string>
            <key>name</key>
            <string>comment.block.spp</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.spp</string>
              </dict>
            </dict>
            <key>match</key>
            <string>(//).*$\n?</string>
            <key>name</key>
            <string>comment.line.double-slash.spp</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.spp</string>
              </dict>
            </dict>
            <key>match</key>
            <string>(#).*$\n?</string>
            <key>name</key>
            <string>comment.line.number-sign.spp</string>
          </dict>
        </array>
      </dict>
    </dict>
  </dict>
</plist>
