<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>sapphire</string>
    <key>scopeName</key>
    <string>source.spp</string>
    <key>fileTypes</key>
    <array>
      <string>spp</string>
    </array>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#keywords</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#literals</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#comments</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>keywords</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b(var)|(func)|(extern)|(operator)|(class)\b</string>
            <key>name</key>
            <string>storage.type.spp</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(for)|(in)|(if)|(else)|(then)|(while)|(return)\b</string>
            <key>name</key>
            <string>keyword.control.spp</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(new)\b</string>
            <key>name</key>
            <string>keyword.operator.spp</string>
          </dict>
        </array>
      </dict>
      <key>literals</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>".*"</string>
            <key>name</key>
            <string>string.quoted.double.spp</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b([0-9]+)\b</string>
            <key>name</key>
            <string>constant.numeric.spp</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(0x[0-9a-fA-F]+)\b</string>
            <key>name</key>
            <string>constant.numeric.spp</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(0b[0-1]+)\b</string>
            <key>name</key>
            <string>constant.numeric.spp</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b([0-9]*.[0-9]+)\b</string>
            <key>name</key>
            <string>constant.numeric.spp</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(nil)\b</string>
            <key>name</key>
            <string>constant.language.spp</string>
          </dict>
        </array>
      </dict>
      <key>comments</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>/\*</string>
            <key>captures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.spp</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\*/</string>
            <key>name</key>
            <string>comment.block.spp</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.spp</string>
              </dict>
            </dict>
            <key>match</key>
            <string>(//).*$\n?</string>
            <key>name</key>
            <string>comment.line.double-slash.spp</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.spp</string>
              </dict>
            </dict>
            <key>match</key>
            <string>(#).*$\n?</string>
            <key>name</key>
            <string>comment.line.number-sign.spp</string>
          </dict>
        </array>
      </dict>
    </dict>
  </dict>
</plist>
