-include $(ROOT_PROJECT_DIRECTORY)options.mk
-include $(ROOT_PROJECT_DIRECTORY)src/dependencies.mk
LIBRARIES= $(sapphire)
TARGET=$(BIN_DIRECTORY)sapphire
-include $(ROOT_PROJECT_DIRECTORY)src/executable.mk
